General:
  ScaleColor: ''
  ScaleFontSize: 10
  ScaleHeight: 90
  ScalePosition: Bottom Right
  ScaleSize: 1000
  beamlinePCHostName: hasm5570cq
  connect_model_startup: true
  darkstyle: false
  db: tango://hasp029rack.desy.de:10000
Motors:
  exp_mot03: bliss://hasep25lab01:25000/xlab_session_2/x2pitch
  exp_mot04: bliss://hasep25lab01:25000/xlab_session_2/x2pitch
  samly: bliss://hasep25lab01:25000/xlab_session_2/x2pitch
  samlz: bliss://hasep25lab01:25000/xlab_session_2/x2pitch
synopticViewer:
  camera_sources:
  - model: tango://hasep25lab01:10000/sys/tg_test/1/uchar_image_ro
    type: 2D
  - model: tango://hasep25lab01:10000/sys/tg_test/1/ulong64_image_ro
    type: 2D
  - model: tango://hasp029rack:10000/sys/tg_test/1/short_image_ro
    type: 2D
viewerTabWidgetVisibility:
  CameraStream:
    index: 0
    show: true
  SardanaSequencer:
    index: 1
    show: false
  configEditor:
    index: 10
    show: true
  imageReg:
    index: 9
    show: true
  motorViewer:
    index: 4
    show: false
  onlineMonitor:
    index: 3
    show: false
  scanQueue:
    index: 2
    show: true
  synopticViewer:
    index: 5
    show: true
  taurus1DPlot:
    index: 7
    show: true
  taurus2DPlot:
    index: 8
    show: true
  taurusMotorViewer:
    index: 6
    show: true